#pragma once

// ============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT BY HAND
// Generated by scripts/gen_vision_profiles.py from the canonical seed table.
// Deterministic output (no timestamp) for clean version-control diffs.
//
// Consumed by config/vision_profiles.h via ROBOFEST_VISION_PROFILE_TABLE_DATA.
// Replaced by operator calibration via sim/cv_laptop_protocol.py [E] export,
// or regenerated automatically by the PlatformIO pre-build hook if deleted.
// ============================================================================

#define ROBOFEST_VISION_PROFILE_TABLE_DATA { \
    /* RED mine */ {1u, true, {170u,10u,100u,255u,100u,255u}, true, {165u,15u,70u,255u,60u,190u}, 25.00f, 2500.00f, 0.70f, 0.00f, 400u, {1.00f, 1.35f, 0.62f, 1.05f, 0.88f, 0u, 255u}}, \
    /* YELLOW buried */ {2u, true, {20u,42u,110u,255u,110u,255u}, true, {18u,45u,85u,255u,75u,210u}, 25.00f, 2500.00f, 0.70f, 5.00f, 400u, {1.00f, 1.35f, 0.62f, 1.05f, 0.88f, 0u, 255u}}, \
    /* ORANGE */ {3u, true, {9u,24u,130u,255u,120u,255u}, true, {8u,26u,95u,255u,80u,215u}, 25.00f, 2500.00f, 0.70f, 0.00f, 400u, {1.00f, 10.00f, 0.00f, 1.05f, 0.00f, 0u, 255u}}, \
    /* GREEN */ {4u, true, {35u,86u,80u,255u,80u,255u}, true, {33u,88u,60u,255u,55u,220u}, 25.00f, 2500.00f, 0.70f, 0.00f, 400u, {1.00f, 10.00f, 0.00f, 1.05f, 0.00f, 0u, 255u}}, \
    /* CYAN */ {5u, true, {87u,99u,90u,255u,90u,255u}, true, {85u,101u,65u,255u,65u,225u}, 25.00f, 2500.00f, 0.70f, 0.00f, 400u, {1.00f, 10.00f, 0.00f, 1.05f, 0.00f, 0u, 255u}}, \
    /* BLUE */ {6u, true, {100u,131u,85u,255u,70u,255u}, true, {98u,133u,60u,255u,50u,230u}, 25.00f, 2500.00f, 0.70f, 0.00f, 400u, {1.00f, 10.00f, 0.00f, 1.05f, 0.00f, 0u, 255u}}, \
    /* PURPLE */ {7u, true, {132u,159u,70u,255u,60u,255u}, true, {130u,161u,50u,255u,45u,235u}, 25.00f, 2500.00f, 0.70f, 0.00f, 400u, {1.00f, 10.00f, 0.00f, 1.05f, 0.00f, 0u, 255u}}, \
    /* PINK */ {8u, true, {160u,175u,60u,255u,110u,255u}, true, {158u,177u,40u,255u,80u,235u}, 25.00f, 2500.00f, 0.70f, 0.00f, 400u, {1.00f, 10.00f, 0.00f, 1.05f, 0.00f, 0u, 255u}}, \
    /* WHITE */ {9u, true, {0u,180u,0u,60u,150u,255u}, true, {0u,180u,0u,80u,120u,235u}, 25.00f, 2500.00f, 0.70f, 0.00f, 400u, {1.00f, 10.00f, 0.00f, 1.05f, 0.00f, 0u, 255u}}, \
    /* BLACK */ {10u, true, {0u,180u,0u,140u,0u,55u}, true, {0u,180u,0u,150u,0u,70u}, 25.00f, 2500.00f, 0.70f, 0.00f, 400u, {1.00f, 10.00f, 0.00f, 1.05f, 0.00f, 0u, 255u}} \
}
