<?xml version="1.0"?>
<package format="3">
  <name>robofest_mission</name>
  <version>0.1.0</version>
  <description>Mission state machine, swarm fusion, and safety/geofence supervision.</description>
  <maintainer email="team@robofest.local">RoboFest Team</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>robofest_interfaces</depend>
  <depend>robofest_navigation</depend>
  <depend>std_srvs</depend>
  <depend>action_msgs</depend>
</package>
