#pragma once

#include <stdint.h>

namespace RobofestDrone {

// ============================================================================
// LENS UNDISTORTION (REQ-DER-120, item 20)
// ----------------------------------------------------------------------------
// Applies a calibrated inverse (Brown-Conrady) remap to raw camera frames
// before geometric CV stages run. The map is built once per resolution from
// the intrinsics in config/camera_calibration.h (generated by
// sim/calibrate_camera.py) and cached in PSRAM; when calibration is absent
// or invalid the map is the identity and remap is a cheap pass-through,
// so the pipeline behaves exactly as before calibration is performed.
//
// Coordinates are packed u32 ((src_y << 16) | src_x) per destination pixel.
// ============================================================================

// Builds (or rebuilds when dimensions change) the remap LUT. Returns false
// only on allocation failure.
bool undistort_build_map(uint16_t w, uint16_t h);

// Remaps an RGB565 frame using the current LUT. Returns false when the map
// has not been built for this size or buffers are null.
bool undistort_remap_rgb565(
    const uint8_t* src, uint8_t* dst,
    uint16_t w, uint16_t h);

// True when calibrated intrinsics are loaded and non-degenerate.
bool undistort_is_calibrated();

} // namespace RobofestDrone
