#!/usr/bin/env python3
"""Vision profile header generator / validator for the Robofest firmware.

Part of REQ-DER-1xx (item 19): guarantees config/vision_profiles_generated.h
exists and is structurally valid before every firmware build, removing the
external-toolchain dependency for basic operation.

Modes:
  --if-missing   Generate the file only when absent (used by the PlatformIO
                 pre-build hook). Never overwrites operator calibration.
  --force        Regenerate the default seed table unconditionally.
  --check [PATH] Validate an existing generated header (default:
                 config/vision_profiles_generated.h). Exit 1 on any problem.

The emitted content is deterministic (no timestamps) so git diffs stay clean.
Operator-calibrated headers exported by sim/cv_laptop_protocol.py ([E] key)
use the same ROBOFEST_VISION_PROFILE_TABLE_DATA contract and remain valid
inputs for --check.
"""

import argparse
import os
import re
import sys

DEFAULT_HEADER_RELPATH = os.path.join("..", "config", "vision_profiles_generated.h")
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Shape gate presets - must mirror SHAPE_GATES_* in config/vision_profiles.h.
SHAPE_ANY = (1.00, 10.00, 0.00, 1.05, 0.00, 0, 255)
SHAPE_CIRCLE = (1.00, 1.35, 0.62, 1.05, 0.88, 0, 255)

BLOB_AREA_MIN_PX = 25.0     # Config::BLOB_AREA_MIN_PX
BLOB_AREA_MAX_PX = 2500.0   # Config::BLOB_AREA_MAX_PX
CIRCULARITY_MIN = 0.70      # Config::CIRCULARITY_MIN
MARKER_AREA_NOMINAL_PX = 400  # Config::MARKER_AREA_NOMINAL_PX

# Seed rows mirror the built-in VISION_PROFILE_TABLE exactly so that a
# fresh checkout behaves identically with or without the generated header.
# Row order matters: narrower bands before broader overlapping ones.
SEED_PROFILES = [
    # (type_id, name, primary(hl,hu,sl,su,vl,vu), alt(...), shape, bias)
    (1, "RED mine",    (170, 10, 100, 255, 100, 255), (165, 15, 70, 255, 60, 190), SHAPE_CIRCLE, 0.0),
    (2, "YELLOW buried", (20, 42, 110, 255, 110, 255), (18, 45, 85, 255, 75, 210), SHAPE_CIRCLE, 5.0),
    (3, "ORANGE",      (9, 24, 130, 255, 120, 255), (8, 26, 95, 255, 80, 215), SHAPE_ANY, 0.0),
    (4, "GREEN",       (35, 86, 80, 255, 80, 255), (33, 88, 60, 255, 55, 220), SHAPE_ANY, 0.0),
    (5, "CYAN",        (87, 99, 90, 255, 90, 255), (85, 101, 65, 255, 65, 225), SHAPE_ANY, 0.0),
    (6, "BLUE",        (100, 131, 85, 255, 70, 255), (98, 133, 60, 255, 50, 230), SHAPE_ANY, 0.0),
    (7, "PURPLE",      (132, 159, 70, 255, 60, 255), (130, 161, 50, 255, 45, 235), SHAPE_ANY, 0.0),
    (8, "PINK",        (160, 175, 60, 255, 110, 255), (158, 177, 40, 255, 80, 235), SHAPE_ANY, 0.0),
    (9, "WHITE",       (0, 180, 0, 60, 150, 255), (0, 180, 0, 80, 120, 235), SHAPE_ANY, 0.0),
    (10, "BLACK",      (0, 180, 0, 140, 0, 55), (0, 180, 0, 150, 0, 70), SHAPE_ANY, 0.0),
]

VISION_PROFILE_MAX = 16


def _ub(v):
    return "%du" % int(round(v))


def build_default_header():
    rows = []
    for tid, name, pb, ab, shape, bias in SEED_PROFILES:
        row = (
            "/* {name} */ "
            "{{{tid}u, true, "
            "{{{p0},{p1},{p2},{p3},{p4},{p5}}}, true, "
            "{{{a0},{a1},{a2},{a3},{a4},{a5}}}, "
            "{mn:.2f}f, {mx:.2f}f, {circ:.2f}f, {bias:.2f}f, {exp}u, "
            "{{{s0:.2f}f, {s1:.2f}f, {s2:.2f}f, {s3:.2f}f, {s4:.2f}f, {c0}u, {c1}u}}"
            "}}"
        ).format(
            name=name, tid=tid,
            p0=_ub(pb[0]), p1=_ub(pb[1]), p2=_ub(pb[2]),
            p3=_ub(pb[3]), p4=_ub(pb[4]), p5=_ub(pb[5]),
            a0=_ub(ab[0]), a1=_ub(ab[1]), a2=_ub(ab[2]),
            a3=_ub(ab[3]), a4=_ub(ab[4]), a5=_ub(ab[5]),
            mn=BLOB_AREA_MIN_PX, mx=BLOB_AREA_MAX_PX,
            circ=CIRCULARITY_MIN, bias=bias,
            exp=int(MARKER_AREA_NOMINAL_PX),
            s0=shape[0], s1=shape[1], s2=shape[2], s3=shape[3],
            s4=shape[4], c0=shape[5], c1=shape[6],
        )
        rows.append("    " + row)
    body = ", \\\n".join(rows)
    return (
        "#pragma once\n"
        "\n"
        "// ============================================================================\n"
        "// AUTO-GENERATED FILE - DO NOT EDIT BY HAND\n"
        "// Generated by scripts/gen_vision_profiles.py from the canonical seed table.\n"
        "// Deterministic output (no timestamp) for clean version-control diffs.\n"
        "//\n"
        "// Consumed by config/vision_profiles.h via ROBOFEST_VISION_PROFILE_TABLE_DATA.\n"
        "// Replaced by operator calibration via sim/cv_laptop_protocol.py [E] export,\n"
        "// or regenerated automatically by the PlatformIO pre-build hook if deleted.\n"
        "// ============================================================================\n"
        "\n"
        "#define ROBOFEST_VISION_PROFILE_TABLE_DATA { \\\n"
        "%s \\\n"
        "}\n" % body
    )


ROW_RE = re.compile(
    r"\{\s*(\d+)u\s*,\s*(true|false)\s*,"
    r"\s*\{\s*(\d+)u\s*,\s*(\d+)u\s*,\s*(\d+)u\s*,\s*(\d+)u\s*,\s*(\d+)u\s*,\s*(\d+)u\s*\}\s*,"
    r"\s*(true|false)\s*,"
    r"\s*\{\s*(\d+)u\s*,\s*(\d+)u\s*,\s*(\d+)u\s*,\s*(\d+)u\s*,\s*(\d+)u\s*,\s*(\d+)u\s*\}\s*,"
    r"\s*(-?[\d.]+)f\s*,\s*(-?[\d.]+)f\s*,\s*(-?[\d.]+)f\s*,\s*(-?[\d.]+)f\s*,\s*(\d+)u\s*,"
    r"\s*\{\s*(-?[\d.]+)f\s*,\s*(-?[\d.]+)f\s*,\s*(-?[\d.]+)f\s*,\s*(-?[\d.]+)f\s*,"
    r"\s*(-?[\d.]+)f\s*,\s*(\d+)u\s*,\s*(\d+)u\s*\}\s*\}",
    re.S,
)


def validate_header_text(text):
    """Validate a generated header body. Returns (ok, list_of_problems, n_rows)."""
    problems = []
    m = re.search(r"#define\s+ROBOFEST_VISION_PROFILE_TABLE_DATA\s*\{(.*)\}\s*$",
                  text, re.S | re.M)
    if not m:
        return False, ["Missing ROBOFEST_VISION_PROFILE_TABLE_DATA define"], 0
    body = m.group(1)
    rows = ROW_RE.findall(body)
    if not rows:
        return False, ["No parsable VisionProfileDef rows found"], 0
    seen_ids = set()
    for r in rows:
        vals = [int(v) if v.isdigit() else float(v) if "." in v or "-" in v else v
                for v in r]
        tid = int(r[0])
        if tid in seen_ids:
            problems.append("Duplicate marker_type_id %d" % tid)
        seen_ids.add(tid)
        # Primary + alt hue bands: h_min <= h_max OR wraparound (h_min > h_max).
        for base in (2, 9):
            hl, hu = int(r[base]), int(r[base + 1])
            sl, su = int(r[base + 2]), int(r[base + 3])
            vl, vu = int(r[base + 4]), int(r[base + 5])
            if not (0 <= hl <= 180 and 0 <= hu <= 180):
                problems.append("Row %d: hue outside 0..180 (%d..%d)" % (tid, hl, hu))
            if not (0 <= sl <= su <= 255):
                problems.append("Row %d: S band invalid (%d..%d)" % (tid, sl, su))
            if not (0 <= vl <= vu <= 255):
                problems.append("Row %d: V band invalid (%d..%d)" % (tid, vl, vu))
        min_area = float(r[15])
        max_area = float(r[16])
        if min_area < 0 or max_area <= min_area:
            problems.append("Row %d: area gate invalid (%.2f..%.2f)" % (tid, min_area, max_area))
        circ = float(r[17])
        if not (0.0 <= circ <= 1.0):
            problems.append("Row %d: circularity_min out of range (%.2f)" % (tid, circ))
        corners_lo, corners_hi = int(r[-2]), int(r[-1])
        if corners_lo > corners_hi:
            problems.append("Row %d: corner gate inverted" % tid)
    if len(seen_ids) > VISION_PROFILE_MAX:
        problems.append("Profile count %d exceeds VISION_PROFILE_MAX %d"
                        % (len(seen_ids), VISION_PROFILE_MAX))
    ok = not problems
    return ok, problems, len(rows)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--if-missing", action="store_true",
                    help="generate only when the header is absent")
    ap.add_argument("--force", action="store_true",
                    help="regenerate the seed header even if present")
    ap.add_argument("--check", nargs="?", default=None, const="__default__",
                    metavar="PATH", help="validate an existing generated header and exit")
    args = ap.parse_args()

    out_path = os.path.normpath(os.path.join(SCRIPT_DIR, DEFAULT_HEADER_RELPATH))

    if args.check is not None:
        path = out_path if args.check == "__default__" else os.path.abspath(args.check)
        if not os.path.isfile(path):
            print("[GEN_PROFILES][ERROR] Header not found: %s" % path)
            return 1
        with open(path, "r") as f:
            text = f.read()
        ok, problems, n_rows = validate_header_text(text)
        if ok:
            print("[GEN_PROFILES] OK: %s (%d profiles valid)" % (path, n_rows))
            return 0
        for p in problems:
            print("[GEN_PROFILES][ERROR] %s: %s" % (path, p))
        return 1

    if os.path.isfile(out_path) and not args.force:
        if args.if_missing:
            return 0
        print("[GEN_PROFILES] Header already exists at %s (use --force to regenerate)." % out_path)
        return 0

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", newline="\n") as f:
        f.write(build_default_header())
    print("[GEN_PROFILES] Wrote default seed header: %s" % out_path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
