#!/usr/bin/env python3
"""Camera intrinsic calibration tool for the Robofest OV5640 rig.

REQ-DER-120 (item 20): captures checkerboard views (live USB/DroidCam/IP
source or a folder of stills), runs OpenCV's Zhang calibration, and exports
the intrinsics as `config/camera_intrinsics.h` for the firmware undistortion
stage - replacing the hardcoded FOV constants' implicit pinhole assumption.

Usage:
    python sim/calibrate_camera.py --camera 0 --rows 6 --cols 9 --square-mm 25
    python sim/calibrate_camera.py --stills ./calib_shots --rows 6 --cols 9

Tips:
    - Capture 15-25 views; move the board to cover all frame regions and
      tilts (~30 deg max).
    - Keep focus and zoom FIXED at flight configuration (tape the lens ring).
    - Accept the header only when mean reprojection error < 0.5 px.
"""

import argparse
import os
import sys

import cv2
import numpy as np

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_HEADER = os.path.normpath(
    os.path.join(SCRIPT_DIR, "..", "config", "camera_intrinsics.h"))

HEADER_TEMPLATE = """#pragma once

// ============================================================================
// AUTO-GENERATED CAMERA INTRINSICS - DO NOT EDIT BY HAND
// Generated by sim/calibrate_camera.py on {ts}
// Checkerboard: {rows} x {cols} inner corners, {sq:.1f} mm squares,
// {views} views used, mean reprojection error {err:.4f} px
//
// Consumed by src/undistort.cpp (REQ-DER-120, item 20). Delete this file or
// set VISION_UNDISTORT_ENABLED=0 to fall back to the uncalibrated pinhole.
// ============================================================================

#include <stdint.h>

namespace RobofestDrone {{
namespace Config {{

constexpr bool   CAM_INTRINSICS_VALID   = true;
constexpr uint16_t CAM_CALIB_WIDTH      = {width}u;
constexpr uint16_t CAM_CALIB_HEIGHT     = {height}u;

constexpr float  CAM_FX_PX              = {fx:.4f}f;
constexpr float  CAM_FY_PX              = {fy:.4f}f;
constexpr float  CAM_CX_PX              = {cx:.4f}f;
constexpr float  CAM_CY_PX              = {cy:.4f}f;

constexpr float  CAM_K1                 = {k1:.8f}f;
constexpr float  CAM_K2                 = {k2:.8f}f;
constexpr float  CAM_P1                 = {p1:.8f}f;
constexpr float  CAM_P2                 = {p2:.8f}f;

}} // namespace Config
}} // namespace RobofestDrone
"""


def collect_from_camera(src, rows, cols, needed):
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
    objp = np.zeros((rows * cols, 3), np.float32)
    objp[:, :2] = np.mgrid[0:cols, 0:rows].T.reshape(-1, 2)

    cap = cv2.VideoCapture(src)
    if not cap.isOpened():
        raise SystemExit(f"cannot open source {src}")

    obj_points, img_points, size = [], [], None
    print("Press [SPACE] to capture a view, [Q] to finish early.")
    while len(obj_points) < needed:
        ok, frame = cap.read()
        if not ok:
            continue
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        found, corners = cv2.findChessboardCorners(
            gray, (cols, rows), None)

        vis = frame.copy()
        if found:
            cv2.drawChessboardCorners(vis, (cols, rows), corners, found)
        cv2.putText(vis, f"views: {len(obj_points)}/{needed}",
                    (10, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.8,
                    (0, 255, 0), 2)
        cv2.imshow("calibration", vis)
        key = cv2.waitKey(1) & 0xFF

        if key == ord('q'):
            break
        if key == ord(' ') and found:
            corners2 = cv2.cornerSubPix(
                gray, corners, (11, 11), (-1, -1), criteria)
            obj_points.append(objp.copy())
            img_points.append(corners2)
            size = (gray.shape[1], gray.shape[0])
            print(f"  captured view {len(obj_points)}")
    cap.release()
    cv2.destroyAllWindows()
    return obj_points, img_points, size


def collect_from_stills(folder, rows, cols):
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)
    objp = np.zeros((rows * cols, 3), np.float32)
    objp[:, :2] = np.mgrid[0:cols, 0:rows].T.reshape(-1, 2)

    obj_points, img_points, size = [], [], None
    files = sorted(f for f in os.listdir(folder)
                   if f.lower().endswith((".png", ".jpg", ".jpeg")))
    for fname in files:
        img = cv2.imread(os.path.join(folder, fname))
        if img is None:
            continue
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        found, corners = cv2.findChessboardCorners(gray, (cols, rows), None)
        if not found:
            print(f"  skip {fname}: no board")
            continue
        corners2 = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)
        obj_points.append(objp.copy())
        img_points.append(corners2)
        size = (gray.shape[1], gray.shape[0])
        print(f"  used {fname}")
    return obj_points, img_points, size


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--camera", help="USB index / rtsp / droidcam:// URL")
    src.add_argument("--stills", help="folder of calibration photos")
    ap.add_argument("--rows", type=int, default=6, help="inner corner rows")
    ap.add_argument("--cols", type=int, default=9, help="inner corner cols")
    ap.add_argument("--square-mm", type=float, default=25.0)
    ap.add_argument("--views", type=int, default=20)
    ap.add_argument("--out", default=DEFAULT_HEADER)
    args = ap.parse_args()

    if args.stills:
        obj_pts, img_pts, size = collect_from_stills(
            args.stills, args.rows, args.cols)
    else:
        cam_src = args.camera
        if cam_src.startswith("droidcam://"):
            rest = cam_src[len("droidcam://"):]
            if ":" not in rest:
                rest += ":4747"
            cam_src = f"http://{rest}/video"
        elif cam_src.isdigit():
            cam_src = int(cam_src)
        obj_pts, img_pts, size = collect_from_camera(
            cam_src, args.rows, args.cols, args.views)

    if len(obj_pts) < 8 or size is None:
        raise SystemExit("need at least 8 usable views")

    rms, mtx, dist, _, _ = cv2.calibrateCamera(
        obj_pts, img_pts, size, None, None)

    fx, fy = mtx[0, 0], mtx[1, 1]
    cx, cy = mtx[0, 2], mtx[1, 2]
    k1, k2, p1, p2 = dist.ravel()[:4]

    print("=" * 60)
    print(f"RMS reprojection error: {rms:.4f} px over {len(obj_pts)} views")
    print(f"fx={fx:.2f} fy={fy:.2f} cx={cx:.2f} cy={cy:.2f}")
    print(f"k1={k1:.6f} k2={k2:.6f} p1={p1:.6f} p2={p2:.6f}")
    if rms > 0.5:
        print("WARNING: error > 0.5 px - consider recapturing cleaner views.")

    import datetime
    header = HEADER_TEMPLATE.format(
        ts=datetime.datetime.now().isoformat(timespec="seconds"),
        rows=args.rows, cols=args.cols, sq=args.square_mm,
        views=len(obj_pts), err=rms,
        width=size[0], height=size[1],
        fx=fx, fy=fy, cx=cx, cy=cy, k1=k1, k2=k2, p1=p1, p2=p2)

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w") as f:
        f.write(header)
    print(f"wrote {args.out}")


if __name__ == "__main__":
    sys.exit(main())
